server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: jukebox-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  r2dbc:
    url: r2dbc:mysql://localhost:3306/touchtunes_db?serverTimezone=-04:00
    username: root
    password: root

    sql:
      init:
        mode: always

  redis:
    host: localhost
    port: 6379


jukebox:
  id: jukebox-129              # 👉 À personnaliser ou à passer en paramètre externe (ex: --jukebox.id=12345)
  topic: jukebox-events
  group-id: jukebox-consumer-${jukebox.id}
