server:
  port: 8080

spring:
  application:
    name: producer

  r2dbc:
    url: r2dbc:mysql://localhost:3306/touchtunes_db?serverTimezone=-04:00
    username: root
    password: root

    sql:
      init:
        mode: always

  datasource:
    url: jdbc:mysql://localhost:3306/touchtunes_db?serverTimezone=-04:00
    username: root
    password: root

    flyway:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: touchtunes_mongo
      username: admin
      password: admin
      authentication-database: admin
      auto-index-creation: true

  r2dbc.properties:
    loggerLevel: DEBUG

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    admin:
      properties:
        bootstrap.servers: localhost:9092

logging:
  level:
    org.springframework.r2dbc.core: DEBUG
    io.r2dbc.spi: DEBUG

partition:
  number: 5

eventapi:
  kafka:
    topic: jukebox-events     # Remplace par le nom réel de ton topic Kafka
    groupId: events-group    # Remplace par le groupId de ton consumer

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

